### API REQUESTS

## Media resource

###  GET ALL MEDIA ITEMS
GET http://localhost:3000/api/media

### GET ID
GET http://localhost:3000/api/media/9590?format=json

### GET ID
GET http://localhost:3000/api/media/2



### POST  Create an item
POST http://localhost:3000/api/media
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="title"

New cat image
------Boundary
Content-Disposition: form-data; name="user_id"

1
------Boundary
Content-Disposition: form-data; name="file"; filename="image.jpg"
Content-Type: image/png

< ./cat2.png
------Boundary--

### DELETE todo
DELETE http://localhost:3000/api/media/1  

### MODIFY ITEM -- ei toimi

PUT http://localhost:3000/api/media/9590
Content-type: application/json

{
    "title": "Basement modified",
    "description": "Some new description",
}

// USERS

###

###  GET ALL USERS
GET http://localhost:3000/api/user

### GET USER ID
GET http://localhost:3000/api/user/305

### ADD USER
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "username": "Meikä Mandariini",
    "password": "******",
    "email": "mm@example.com",
    "user_level_id": 1,
    "created_at": "2024-11-23W06:56:41.000Z"
}

### DELETE USER

DELETE http://localhost:3000/api/user/305





### CREATE NEW MEDIA ITEM

POST http://localhost:3000/api/media
Content-Type: application/json

{
    "filename": "lisätty_katti.jpg",
    "filesize": 887574,
    "title": "Uusi kissa",
    "description": "Lisätty kissakuva",
    "user_id": 1606,
    "media_type": "image/jpeg",
    "created_at": "2023-10-16T19:00:09.000Z"
  }