### API REQUESTS


### USERS


###  GET ALL USERS
GET http://localhost:3000/api/user

### GET USER ID
GET http://localhost:3000/api/user/2


### DELETE USER
DELETE http://localhost:3000/api/user/5


### LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "NewUser",
    "password": "salasana"
}


### Get USER INFO
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiaWF0IjoxNzMyNjQwODcyLCJleHAiOjE3MzI3MjcyNzJ9.yqV93MuNiDQrVgK6C4GqaGNaNzjn5uG73hBkftGKCNo

### USER VALIDATION - auth routerin kautta
### REGISTER - Lisää uusi käyttäjä POST
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "NewUser",
    "password": "salasana",
    "email": "user@example.com"
}

### REGISTER fail - ei mene validoinnista läpi
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "r",
    "password": "salla",
    "email": "newr@example.com"
}

### LOGIN - fail
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}




## Media resource

###  GET ALL MEDIA ITEMS
GET http://localhost:3000/api/media


### GET media by ID
GET http://localhost:3000/api/media/2



### POST LISÄÄ UUS ITEMI Auth
POST http://localhost:3000/api/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiaWF0IjoxNzMyNjQwODcyLCJleHAiOjE3MzI3MjcyNzJ9.yqV93MuNiDQrVgK6C4GqaGNaNzjn5uG73hBkftGKCNo
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="title"

Lisätty kuva autentikoinnilla
------Boundary
Content-Disposition: form-data; name="description"

Poistetaan tämä kuva 
------Boundary
Content-Disposition: form-data; name="file"; filename="image.jpg"
Content-Type: image/png

< ./cat2.png
------Boundary--

### PUT MODIFY ITEM

PUT http://localhost:3000/api/media/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiaWF0IjoxNzMyNjQwODcyLCJleHAiOjE3MzI3MjcyNzJ9.yqV93MuNiDQrVgK6C4GqaGNaNzjn5uG73hBkftGKCNo

{
  "title": "NEW TITLE FROM PUT with authorization",
  "description": "Muokataan ja poistetaan tämä kuva kohta"
}


### DELETE MEDIA ITEM AUTH
DELETE http://localhost:3000/api/auth/delete/media/200
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiaWF0IjoxNzMyNjQwODcyLCJleHAiOjE3MzI3MjcyNzJ9.yqV93MuNiDQrVgK6C4GqaGNaNzjn5uG73hBkftGKCNo

### DELETE Media Item
DELETE http://localhost:3000/api/media/6




# {
#     "username": "JohnDoe",
#     "password": "to-be-hashed-pw1"
# }



